import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import SiteNav from "./components/nav/SiteNav";
import SiteHeaderClient from "./components/nav/SiteNav";
//import { GoogleReCaptchaProvider } from "react-google-recaptcha-v3";
import RecaptchaProvider from "./components/providers/RecaptchaProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RecaptchaProvider
        >
         <Providers>
        <SiteNav/>
        {children}</Providers> 
        </RecaptchaProvider>    
      </body>
    </html>
  );
}
