// src/lib/skills/skill-taxonomy.ts
export const POPULAR_SKILLS: string[] = [
    "Communication",
    "Customer Service",
    "Sales",
    "Leadership",
    "Project Management",
    "Time Management",
    "Problem Solving",
    "Microsoft Excel",
    "Microsoft Office",
    "Data Entry",
    "Scheduling",
    "Teamwork",
    "Negotiation",
    "Public Speaking",
    "SQL",
    "Python",
    "JavaScript",
    "React",
    "Node.js",
    "TypeScript",
    "AWS",
    "Docker",
    "Git",
    "Agile",
    "Scrum",
  ];
  
  export const SKILL_DICTIONARY: string[] = [
    ...new Set([
      ...POPULAR_SKILLS,
      "Operations",
      "People Management",
      "Business Analysis",
      "Stakeholder Management",
      "Marketing",
      "SEO",
      "Content Writing",
      "Copywriting",
      "Graphic Design",
      "Figma",
      "UI/UX",
      "Accounting",
      "Bookkeeping",
      "Cash Handling",
      "Inventory Management",
      "Retail",
      "Nursing",
      "Medical Assisting",
      "EMR",
      "HIPAA",
      "Forklift",
      "Construction",
      "Electrical",
      "Plumbing",
      "Welding",
    ]),
  ];
  